### ISSUE TITLE
"API questions/suggestions"

### ISSUE THREAD

**Issue by k2b6s9j** [AtomLinter/linter-plus#48]
### Original Ticket Opening Text from AtomLinterPlus/linter-plus#3 by @lierdakil
While reading wiki page on service-provider API, I found some decisions a little bit puzzling.

Here's a list of what immediately popped into my mind:

1. Why pass both editor and buffer to `lint`? Buffer is always available through `getBuffer()`, and in most cases editor reference is not needed at all, since plumbing should be handled by AtomLinter anyway.
2. While on topic, why use positional parameters as arguments to `lint`, and not an object? Using object would be considerably more flexible with little overhead, using CoffeeScript's argument object unpacking. Of course, if you choose to use a single `editor` argument, that's not applicable.
3. `scope` and `scopes` seem a little misleading names. Something more descriptive, like `grammarScopes` and `linterScope` would be a bit better.
4. Same goes for Message and Trace fields: `position` is not position, but range, and `file` is not a file, but a URI (presumably), or file path (if you prefer), so `fileURI`/`filePath` might be more descriptive (btw, is it absolute or relative to project directory?). `message` and `html` could be a little more descriptive as well, but I'm not sure I understand semantics correctly, so I can't offer any options on `html`. I'd rename `message` to `text`, though, since whole object itself is semantically a "message".

That's from the top of my head.

### Image Archive of Original Conversation
![image](https://cloud.githubusercontent.com/assets/594124/8075839/73bd3b8c-0f02-11e5-9d64-866a0fad5d8e.png)

### Everyone Involved in Original Conversation
@lierdakil
@steelbrain
@k2b6s9j

**Comment by lierdakil** [comment]
A couple more weird quirks I found when trying to test this API as well.

1. `position` doesn't accept `new Range`, and only worked with array in my experience. This should be fixed.
2. Again, `position` uses 1-based indexing, while everything else in Atom uses 0-based indexing for `Range` and `Position`. You can see this clearly by trying to display error at current cursor position. I understand that most linters use 1-based indexing, but this feels weird and inconsistent.

**Comment by steelbrain** [comment]
@lierdakil position doesn't accept a range because the programs provide a format of line 1 char 5 and atom expects it to be line 0 char 4. so instead of doing this in each provider, we decided to do it in the core.  (it also answers point 2)

**Comment by lierdakil** [comment]
First, docs are *very* misleading then. Second, this is inconsistent with *everything* else. One option that might leave convenience in place, while allowing for some consistency would be to have *two* fields, e.g. `range`, which is zero-based and accepts `class Range`, and one, e.g. `rangeBase1`, which would keep current semantics. That said, I prefer to use `class Range` instead of array in all cases, since it's more self-documenting, so to speak. But then again, I use zero-based indexing everywhere.

**Comment by lierdakil** [comment]
Obviously provider would then set one or the other.

**Comment by steelbrain** [comment]
I get your point, we could accept Range objects and leave them unchanged, and accept a range like array and change it to match atom's style. How does that sound to You?

I want to keep the 1-based indexing because when a person writes a provider, he uses let's say coffeelint, and coffeelint says there's an error on `Line #4`, the person won't have to write `Line #3`, he can pass the direct values and we can normalize them in the core.

**Comment by lierdakil** [comment]
I feel like this would still be inconsistent, so at least docs should clearly emphasize this. But this would fit my use-case well enough, so that's fine by me.

Though I still think that having two mutually exclusive fields for this is a better option, I defer to your judgement on this.

**Comment by steelbrain** [comment]
Your idea of having two different fields is appealing, what do you suggest their names to be?

**Comment by lierdakil** [comment]
There could be a couple of options, but I'm not sure what would communicate intent best.

First one, is to have `range` and `rangeBase1`, as per my previous comment. This is not ideal though, now that I think about it.
Second one that immediately comes to mind is to have `atomRange` and `linterRange`, which is somewhat better.
Third one, if you're willing to have *long* field names (something I'm reluctant to endorse), would be `zeroBasedRange` and `oneBasedRange`. This would be literally what they are, but that is a mouthful.

One another option that I just thought of is to use *one* field for ranges, and *another* as a "switch", e.g.

```cson
range: new Range ...
rangeIsZeroBased: true # not sure of what default should be,
# since "true" would be consistent with Atom, and "false" -- with older Linter versions
```

Or, for more general approach:
```cson
range: ...
rangeIndexBase: 0 # or 1. Not sure 2 and up would make much sense
```

Last idea actually looks quite nice. Thoughts?

**Comment by k2b6s9j** [comment]
How about:

```coffeescript
range: new Range ...
base: 0 # or 1
```

**Comment by steelbrain** [comment]
Or how about you make the input 1-indexed :stuck_out_tongue: 'cause Your package is it's only use-case.

**Comment by lierdakil** [comment]
@steelbrain, look, frankly, I'm fine *without* Linter, so I'm not *too* concerned about its API. But if you're aiming to bundle it with Atom, I think you need your API to be somewhat consistent with the rest of core. Base-1 ranges are not, but are convenient. I offer ways to reconcile that somewhat (what I can think of, anyway). @k2b6s9j asked for my input, so I provide it. To be blunt, you're free to do whatever you want with it.

@k2b6s9j, while `range` is self-explanatory, `base` is not. Since this option would have a sensible default (whatever that would be), I don't think it's mandatory to find a shorter name for it, and having a more descriptive name would be preferable. Personally, I strongly believe that most names in an API should be somewhat self-explanatory, since it allows for much more readable code, which, in collaborative development, is a must, IMO.

**Comment by steelbrain** [comment]
You know what, You're right, We should be dealing with this in every linter, instead of the base package itself, 'cause that's how the core does it.

**Comment by lierdakil** [comment]
That's a great attitude you've got there. Notice I'm not advocating you should switch to 0-based ranges completely. But you know what? I've wasted enough time and effort on this. If you're not in the mood for a discussion on how to make this work, suit yourself. I don't think I want to engage in this conversation any longer.

**Comment by steelbrain** [comment]
There wasn't any sarcasm in there, I was serious, 'cause if the people make their ranges 0-based to interact with core, then why not with linter?

**Comment by AsaAyers** [comment]
@lierdakil sorry for your troubles here. I have the same issue trying to contribute here recently.

It sounds to me like for consistency we should probably use a base-0 `range` that actually accepts a `Range`. It only makes sense since we're handing the linter the editor/buffer.

In the chat room we had discussed providing a utility service for CLI linters. The utility should have a helper for converting these. After seconds of thought I'm thinking:

    range = linterUtils.toRange( [
        [1, 1], # line 1 column 1 (as you would see in your editor)
        [1, 5]
    ])
    range.start.row === 0
    range.start.col === 0

**Comment by AsaAyers** [comment]
fyi, the gitter room is https://gitter.im/AtomLinter/Linter if you'd like to join us

**Comment by lierdakil** [comment]
@steelbrain, sorry, I just assumed based on previous resistance to the idea. Written conversation doesn't convey tone well, I guess.

**Comment by AsaAyers** [comment]
The more I think about it the more I'm sure that because the input is an Editor/Buffer (0-indexed) the output should match even if in between the linters have to do the conversion. Possibly through a convenient utility we provide.

**Comment by lierdakil** [comment]
@AsaAyers, utility *service* might be a little awkward to work with. Maybe an npm package would be more convenient? Just a thought.

**Comment by AsaAyers** [comment]
The discussion happened on gitter and @joefitzgerald has a plan. IIRC it's what AutoComplete+ does.

**Comment by lierdakil** [comment]
I'm kind of bad with real-time chats, like gitter, so I will try to convey my thoughts here.

Using a service is somewhat awkward. One would need to 
- define a consumed service in `package.json`
- store a service object returned somewhere
- thread it around everywhere it's needed

Not ideal, IMO.

In contrast, using npm package is as simple as adding a line to `package.json` and then `require`ing it only when it's needed, e.g.
```coffeescript
{toRange} = require 'linter-helpers'
```

This is, of course, at a cost of additional headache maintaining npm package. On the other hand, it's less code bloat in core (I think that's why space pen was moved to separate package, at least in part)

AC+ doesn't provide any services, only consumes one.

**Comment by steelbrain** [comment]
@lierdakil position has been renamed to `range` and ranges are accepted as 0-based in #54

**Comment by lierdakil** [comment]
Great!

As a reminder, other API changes I think we agreed upon

- [ ] Drop `buffer` argument to `lint`, since it's always available via `editor.getBuffer()`
- [ ] Rename `scope` -> `linterScope`, since `scope` and `scopes` can be confusing
- [ ] Rename `scopes` -> `grammarScopes`, since `scope` and `scopes` can be confusing
- [ ] Rename `message` -> `text`, since whole object is technically a "message"
- [ ] Rename `file` -> `filePath`, for clarity

**Comment by steelbrain** [comment]
The buffer argument has already been removed btw. It was merged a few days ago.

**Comment by lierdakil** [comment]
Missed that. Updated.

**Comment by steelbrain** [comment]
@lierdakil `linterScope` doesn't really sound like a good name, do you have any alternatives in mind?

**Comment by steelbrain** [comment]
@lierdakil All done except `linterScope`

**Comment by lierdakil** [comment]
Not really. This field is meant to specify scope of a given linter, either `file`, or `project`, so... I'm not too happy about this name either, but I can't think of any alternatives, really (maybe it's because English is not my native language). If you wish to stretch it, `extent` might be a synonym for `scope` in this context, but this feels equally weird.

**Comment by lierdakil** [comment]
I guess leaving it as `scope` could be fine, given that `scopes` are renamed.

**Comment by steelbrain** [comment]
@lierdakil now that `scopes` has been renamed to `grammarScopes`, I think it's okay to leave it as scope.

**Comment by steelbrain** [comment]
We wrote the same thing at the same time, Hahaha

**Comment by lierdakil** [comment]
This settles it then.

**Comment by steelbrain** [comment]
Thank you for your awesome suggestions, We really appreciate it, feel free to re-open if you have more.

**Comment by lierdakil** [comment]
You're welcome. Note that I can't reopen this though :sweat_smile:
Don't worry, I'll just open new one if necessary.
